import { useState, useEffect, useRef, useId } from "react";
import { useNavigate } from "@tanstack/react-router";
import { Search, X, Loader2, Package, ArrowRight } from "lucide-react";
import { getProducts, type ShopifyProduct } from "@/lib/woocommerce";

interface ProductSearchBarProps {
  className?: string;
  inputClassName?: string;
  placeholder?: string;
  autoFocus?: boolean;
  initialQuery?: string;
  onSelectProduct?: (product: ShopifyProduct) => void;
  id?: string;
}

export function ProductSearchBar({
  className = "",
  inputClassName = "",
  placeholder = "Buscar productos por nombre, categoría...",
  autoFocus = false,
  initialQuery = "",
  onSelectProduct,
  id: customId,
}: ProductSearchBarProps) {
  const [query, setQuery] = useState(initialQuery);
  const [results, setResults] = useState<ShopifyProduct[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isOpen, setIsOpen] = useState(false);
  const [selectedIndex, setSelectedIndex] = useState<number>(-1);

  const containerRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const autoGeneratedId = useId();
  const inputId = customId || `search-input-${autoGeneratedId}`;
  const navigate = useNavigate();

  // Sync with initialQuery when it changes externally
  useEffect(() => {
    setQuery(initialQuery);
  }, [initialQuery]);

  // Debounced search when query changes
  useEffect(() => {
    const trimmed = query.trim();
    if (!trimmed) {
      setResults([]);
      setIsLoading(false);
      setIsOpen(false);
      setSelectedIndex(-1);
      return;
    }

    let isMounted = true;
    setIsLoading(true);
    setIsOpen(true);

    const timer = setTimeout(async () => {
      try {
        const products = await getProducts(8, trimmed);
        if (isMounted) {
          setResults(products);
          setSelectedIndex(-1);
        }
      } catch (err) {
        console.error("Error en búsqueda predictiva:", err);
        if (isMounted) setResults([]);
      } finally {
        if (isMounted) setIsLoading(false);
      }
    }, 200);

    return () => {
      isMounted = false;
      clearTimeout(timer);
    };
  }, [query]);

  // Close dropdown on click outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (containerRef.current && !containerRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  const handleSelect = (product: ShopifyProduct) => {
    setIsOpen(false);
    if (onSelectProduct) {
      onSelectProduct(product);
    } else {
      navigate({
        to: "/product/$handle",
        params: { handle: product.node.handle },
      });
    }
  };

  const handleSubmit = (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    const trimmed = query.trim();
    if (!trimmed) return;

    // If an item is selected via arrows, go directly to that item
    if (selectedIndex >= 0 && results[selectedIndex]) {
      handleSelect(results[selectedIndex]);
      return;
    }

    // Otherwise navigate to /tienda with query
    setIsOpen(false);
    navigate({
      to: "/tienda",
      search: { q: trimmed },
    });
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Escape") {
      setIsOpen(false);
      return;
    }

    if (!isOpen || results.length === 0) {
      if (e.key === "Enter") {
        handleSubmit();
      }
      return;
    }

    if (e.key === "ArrowDown") {
      e.preventDefault();
      setSelectedIndex((prev) => (prev < results.length - 1 ? prev + 1 : 0));
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      setSelectedIndex((prev) => (prev > 0 ? prev - 1 : results.length - 1));
    } else if (e.key === "Enter") {
      e.preventDefault();
      handleSubmit();
    }
  };

  const handleClear = () => {
    setQuery("");
    setResults([]);
    setIsOpen(false);
    setSelectedIndex(-1);
    inputRef.current?.focus();
  };

  return (
    <div
      ref={containerRef}
      className={`product-search-bar relative w-full ${className}`}
      role="search"
    >
      <form onSubmit={handleSubmit} className="relative flex w-full items-center">
        <span className="pointer-events-none absolute left-3.5 flex items-center justify-center text-muted-foreground">
          {isLoading ? (
            <Loader2 size={18} className="animate-spin text-primary" />
          ) : (
            <Search size={18} />
          )}
        </span>

        <input
          ref={inputRef}
          id={inputId}
          name="q"
          type="text"
          value={query}
          autoFocus={autoFocus}
          autoComplete="off"
          spellCheck="false"
          placeholder={placeholder}
          aria-label="Buscar productos"
          aria-expanded={isOpen}
          aria-autocomplete="list"
          aria-controls={`${inputId}-dropdown`}
          onChange={(e) => setQuery(e.target.value)}
          onFocus={() => {
            if (query.trim()) setIsOpen(true);
          }}
          onKeyDown={handleKeyDown}
          className={`h-11 w-full rounded-full border border-border bg-card pl-10 pr-10 text-sm text-foreground shadow-xs outline-none transition-all placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/20 ${inputClassName}`}
        />

        {query && (
          <button
            type="button"
            onClick={handleClear}
            className="absolute right-3 grid h-6 w-6 place-items-center rounded-full text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
            aria-label="Borrar texto de búsqueda"
          >
            <X size={14} />
          </button>
        )}
      </form>

      {/* Predictive Search Dropdown */}
      {isOpen && query.trim().length > 0 && (
        <div
          id={`${inputId}-dropdown`}
          className="absolute left-0 right-0 top-[calc(100%+6px)] z-50 overflow-hidden rounded-2xl border border-border bg-card shadow-xl animate-in fade-in-50 slide-in-from-top-1 duration-150"
        >
          {isLoading && results.length === 0 ? (
            <div className="flex items-center justify-center gap-2 py-8 text-sm text-muted-foreground">
              <Loader2 size={16} className="animate-spin text-primary" />
              <span>Buscando productos en WooCommerce...</span>
            </div>
          ) : results.length > 0 ? (
            <div className="flex flex-col">
              <div className="px-4 py-2 border-b border-border/60 bg-muted/40 text-[11px] font-bold uppercase tracking-wider text-muted-foreground flex justify-between items-center">
                <span>Resultados sugeridos ({results.length})</span>
                <span className="text-[10px] lowercase font-normal opacity-75">
                  Usa ↑ ↓ para navegar
                </span>
              </div>

              <ul className="max-h-[380px] overflow-y-auto divide-y divide-border/40 py-1">
                {results.map((product, index) => {
                  const image = product.node.images.edges[0]?.node;
                  const price = product.node.priceRange.minVariantPrice;
                  const isSelected = selectedIndex === index;

                  return (
                    <li key={product.node.id}>
                      <button
                        type="button"
                        onClick={() => handleSelect(product)}
                        onMouseEnter={() => setSelectedIndex(index)}
                        className={`group flex w-full items-center gap-3.5 px-4 py-3 text-left transition-colors ${
                          isSelected
                            ? "bg-primary-soft text-primary"
                            : "hover:bg-muted/70 text-foreground"
                        }`}
                      >
                        {/* Thumbnail */}
                        <div className="relative h-12 w-12 shrink-0 overflow-hidden rounded-lg border border-border/80 bg-background flex items-center justify-center">
                          {image?.url ? (
                            <img
                              src={image.url}
                              alt={image.altText ?? product.node.title}
                              className="h-full w-full object-contain p-1 transition-transform duration-200 group-hover:scale-105"
                              referrerPolicy="no-referrer"
                              loading="lazy"
                            />
                          ) : (
                            <Package className="text-muted-foreground/50" size={20} />
                          )}
                        </div>

                        {/* Title and Category */}
                        <div className="min-w-0 flex-1">
                          <p className="truncate text-sm font-bold text-foreground group-hover:text-primary transition-colors">
                            {product.node.title}
                          </p>
                          <div className="mt-0.5 flex items-center gap-2 text-xs text-muted-foreground">
                            {product.node.productType && (
                              <span className="truncate max-w-[140px] font-medium text-primary/80">
                                {product.node.productType}
                              </span>
                            )}
                          </div>
                        </div>

                        {/* Price */}
                        <div className="shrink-0 text-right">
                          <span className="text-sm font-black text-primary">
                            {price.currencyCode} {Number(price.amount).toFixed(2)}
                          </span>
                        </div>
                      </button>
                    </li>
                  );
                })}
              </ul>

              {/* Bottom footer button to view all results */}
              <div className="border-t border-border bg-muted/30 p-2 text-center">
                <button
                  type="button"
                  onClick={() => handleSubmit()}
                  className="inline-flex w-full items-center justify-center gap-1.5 rounded-lg py-2 text-xs font-bold text-primary transition-colors hover:bg-primary/10"
                >
                  <span>Ver todos los resultados para “{query.trim()}”</span>
                  <ArrowRight size={14} />
                </button>
              </div>
            </div>
          ) : (
            <div className="p-6 text-center">
              <Package size={28} className="mx-auto mb-2 text-muted-foreground/60" />
              <p className="text-sm font-bold text-foreground">Sin coincidencias</p>
              <p className="mt-1 text-xs text-muted-foreground">
                No encontramos productos que coincidan con “{query.trim()}”.
              </p>
              <button
                type="button"
                onClick={() => handleSubmit()}
                className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-primary hover:underline"
              >
                Explorar todo el catálogo
                <ArrowRight size={12} />
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
